rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::PidTuneTool -> hardware
      - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster

      - rmcs_core::controller::pid::PidController -> velocity_pid_controller
    

velocity_pid_controller:
  ros__parameters:
    measurement: /top/imu/gz
    setpoint: /motor/control_velocity
    control: /motor/control_torque
    kp: 3.0
    ki: 0.02
    kd: 40.0
    integral_min: -30.0
    integral_max: 30.0
    # output_max: 3.0
    # output_min: -3.0

value_broadcaster:
  ros__parameters:
    forward_list:
      - /top/imu/gz
      - /top/imu/gy
      - /bottom/imu/gz
      - /bottom/imu/gy
      - /motor/raw_angle
      - /motor/angle
      - /motor/velocity
      - /motor/angle_error
      - /motor/control_angle
      - /motor/control_velocity
      - /motor/control_velocity_pid
      - /motor/velocity_filtered
      - /motor/control_torque

hardware:
  ros__parameters:
    usb_pid_top_board: 0xa513
    usb_pid_bottom_board: 0x4ca4
    motor_zero_point: 0

    velocity_step: 1.0
    step_time: 400.0

    imu_bias_x: 0
    imu_bias_y: 0
    imu_bias_z: 0

